import MySwiper from "./MySwiper";
import Introduction from "./Introduction";
import Attitude from "./Attitude";
import Ads from "./Ads";
import Rating from "./Rating";
import Keeping from "./Keeping";
import KeepingContent from './KeepingContent'
import Shape from "./Shape";
import ShapeContent from "./ShapeContent";
import History from "./History";
import Collection from "./Collection";

export { MySwiper }
export { Introduction }
export { Attitude }
export { Ads }
export { Rating }
export { Keeping }
export { KeepingContent }
export { Shape }
export { ShapeContent }
export { History }
export { Collection }